general.import = [
  # "~/dotfiles/alacritty/catppuccin-mocha.toml", # catppuccin-mocha theme
  # "~/dotfiles/alacritty/moonfly-default.toml",
  # "~/dotfiles/alacritty/gruvbox-dark-soft-contrast.toml",
  # "~/dotfiles/alacritty/cyberdream.toml",
  "~/dotfiles/alacritty/tokyo-night.toml",
]

[env]
TERM = "xterm-256color"
PYTHONWARNINGS = "ignore"
LANG = "en_US.UTF-8"

[cursor.style]
blinking = "On" # values are =['On', 'Off', 'Always','Never']
shape = "Block"

# dir
[font]
size = 9

[font.normal]
# family = "BigBlueTermPlus Nerd Font"
# family = "FiraCode"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[terminal]
[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "full"
# dynamic_padding = true
# opacity = 0.75
blur = true
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 5
y = 5

# Keybindings
[keyboard]
bindings = [{ key = "`", mods = "Control", action = "ToggleFullscreen" }]
